import React from "react";
import './globals.css'
import {Roboto_Mono} from 'next/font/google'
import Header from "../components/Header";
import ScreenBorder from "../components/FixedAudio";
import ReduxProvider from "../redux/Provider";

const mono = Roboto_Mono({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
    title: "Laura Portfolio",
    description: "Generated by KyeongEun Jo",
    icons: {
        icon: "/images/me.jpeg",
    },
};
export const viewport = {
    initialScale: 1,
    minimumScale: 1,
    maximumScale: 1,
    width: 'device-width',
    userScalable: 'no',
}
export default function RootLayout({ children }) {
    return (
        <html lang="en" id='html'>
            <body className={mono.className} suppressHydrationWarning={true}>
                <ReduxProvider>
                    <div>
                        <ScreenBorder />
                        <Header />
                        {children}
                    </div>
                    <div id='portal-detail' />
                    <div id='portal-contact' />
                </ReduxProvider>
            </body>
        </html>
    )
}
